review/urls.py
from django.urls import path
from .views import create,login,logout,homepage,add_service_form
from .views import myservice,admin_login,auth,main
from .views import myservice,admin_login,auth,admin_home, add_category
from .views import service_category, service_question, delete_category
from .views import search,review,category_review
from .views import reject_service,accept_service,get_question

urlpatterns = [
    path('',main),
    path('create',create),
    path('login',login),
    path('homepage',homepage),
    path('logout',logout),
    path('add_service_form',add_service_form),
    path('myservice/<int:id>',myservice),
    path('admin_login',admin_login),
    path('auth',auth),
    path('admin_home', admin_home),
    path('admin_service_category', service_category),
    path('add_category', add_category),
    path('delete_category', delete_category),
    path('admin_question', service_question),
    path('search',search),
    path('accept_service', accept_service),
    path('reject_service', reject_service),
    path('review',review),
    path('add_review',category_review),
    path('get_question', get_question)
]

reviewpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('review.urls'))   
]

review/models.py
from django.db import models

# Create your models here.


class Org(models.Model):
    company = models.CharField(max_length=100)
    password = models.CharField(max_length=100)


class Org_login(models.Model):
    company = models.CharField(max_length=100)
    password = models.CharField(max_length=100)


class Services(models.Model):
    company = models.CharField(max_length=100)
    service = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    status = models.CharField(max_length=2, default='P')


class Admin(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

class Admin_login(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

class Category(models.Model):
    name = models.CharField(max_length=200)

class Question(models.Model):
	Category_id = models.CharField(max_length=200)
	Question = models.TextField(max_length = 500)

class Review(models.Model):
    Category_id = models.CharField(max_length=200)
    review1 = models.CharField(max_length=100)
    review2 = models.CharField(max_length=100)
    review3 = models.CharField(max_length=100)
    review4 = models.CharField(max_length=100)
    review5 = models.CharField(max_length=100)
    comment = models.TextField(max_length=500)

review/forms.py
from django import forms
from .models import Org,Services,Admin_login
from .models import Admin, Question,Review
class login_form_org(forms.ModelForm):
	class Meta:
		model = Org
		fields = ('company','password')
	confirm_password = forms.CharField(max_length=100)

class login_form(forms.Form):
	company = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100)

class add_service(forms.ModelForm):
	class Meta:
		model = Services
		fields = ('company','service','category','description')

class admin_login_form(forms.Form):
	class Meta:
		model = Admin
	username = forms.CharField(max_length=10)
	password = forms.CharField(max_length=100)
	email = forms.EmailField(max_length=100)

class auth_form(forms.Form):
	otp_test = forms.CharField(max_length=10)
	
class service(forms.ModelForm):
	class Meta:
		model = Question
		fields = ('Category_id','Question')
		
class reviewform(forms.ModelForm):
	class Meta:
		model = Review
		fields = ('Category_id','review1','review2','review3','review4','review5','comment')

templates/acceptRejectDiv.html
{% for obj in pending_services %}
<!-- <div class="row"> -->
<p><span style="font-weight: bold">Company : </span>{{obj.company}}</p>
<p><span style="font-weight: bold">Service : </span>{{obj.service}}</p>
<p><span style="font-weight: bold">Category : </span>{{obj.category}}</p>
<p><span style="font-weight: bold">Description : </span>{{obj.description}}</p>

<div class="float-right">
    <button class="btn btn-success" onclick="accepted('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">A</button>
    <button class="btn btn-danger" onclick="rejected('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">R</button>
</div>
<div class="row"></div>
<br>
<hr>
<!-- </div> -->
{% endfor %}

templates/auth.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
  <span>Hey Admin</span>
</nav><br><br>
<div class="container">

<!-- <form method="post" action="/admin_login">
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="Submit">
</form> -->
<div class="col-4">
	<div class="alert alert-primary" role="alert">
  Almost there....
</div><br>
 <form action="/auth" method="POST" >
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="submit">
</form>
</div>

</div>
</body>

templates/auth_admin.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script>

        function accepted(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/accept_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

        function rejected(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/reject_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

    </script>
</head>

<body>
    <!-- As a link -->

    <!-- As a heading -->
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Review It</span>
        <span>Hey Admin</span>
    </nav><br><br>


    <div class="row">
        <div class="col-2"></div>
        <div class="col-4">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h3 class="card-title">Pending Services to verify</h3>
                    <p class="card-text"></p>
                    <div class="container" id="acceptRejectDiv">
                        {% for obj in pending_services %}
                        <!-- <div class="row"> -->
                        <p><span style="font-weight: bold">Company : </span>{{obj.company}}</p>
                        <p><span style="font-weight: bold">Service : </span>{{obj.service}}</p>
                        <p><span style="font-weight: bold">Category : </span>{{obj.category}}</p>
                        <p><span style="font-weight: bold">Description : </span>{{obj.description}}</p>

                        <div class="float-right">
                            <button class="btn btn-success" onclick="accepted('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">A</button>
                            <button class="btn btn-danger" onclick="rejected('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">R</button>
                        </div>
                        <div class="row"></div>
                        <br>
                        <hr>
                        <!-- </div> -->
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1"></div>
        <div class="col-4">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <a href="/admin_service_category">
                        <button class="btn btn-primary">Service Categories</button>
                    </a>
                    <div class="row"></div>
                    <div class="row"></div>
                    <a href="/admin_question">
                        <button class="btn btn-success">Questions</button>
                    </a>
                </div>
            </div>
        </div>

    </div>

templates/login.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
  /* The image used */
  background-image: url("static/img/login-01.jpg");

  height: auto;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

</style>
</head>
<body>

<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
</nav>

<div class="bg-img">
  <div class="container"><br>
  <h1 class="col-lg-8 text-center" style="color:white">Login here to start reviewing</h1></div>
<div class="container justify-center pt-4 col-lg-4 col-md-12">
  <div class="card">
        <img src="static/img/form-01.jpg" class="card-img-top img-fluid " height="50%">
  <div class="card-header">
    <h2 class="text-center">Login</h2>
  </div>
  <div class="card-body">
    
  <form action="" method="POST" name='form'>
	{% csrf_token %}
	<input type="text" class="form-control form-control-lg" id="id_password" name="company" placeholder="Enter Company"><br><br>
  <input type="password" class="form-control form-control-lg" id="id_confirm_password" name="password" placeholder="Enter Password"><br><br>
  <div class="row">
  
<button type="submit" class="btn btn-lg col-lg-12" style="background-color: orange;"><h3>Submit</h3></button>	</form>
  </div>
  </div>
</div>
</div>
</div>
</body>

templates/login_admin.html
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
		
</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
  <span>Hey Admin</span>
</nav><br><br>
<div class="container">
<!-- <form method="post" action="/admin_login">
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="Submit">
</form> -->
<div class="col-4">
 <form action="/admin_login" method="POST" name='form' class="sm-auto">
	{% csrf_token %}
	<label>Username:</label><br>
	<input type="text" class="form-control" id="id_username" name="username" placeholder="Enter Username">
	<label>Email:</label><br>
	<input type="email" class="form-control" id="id_email" name="email" placeholder="Enter Email">
	<label>Password:</label><br>

	<input type="password" class="form-control" id="id_password" name="password" placeholder="Enter Password"><br>
	<button type="submit" class="btn btn-primary" name="submit">Submit</button>
</form>
</div>
{{ otp }}
{{ error }}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</body>

templates/login_org.html
<head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
		<style>body, html {
				height: 100%;
				font-family: Arial, Helvetica, sans-serif;
			}
			
			* {
				box-sizing: border-box;
			}
			
			.bg-img {
				/* The image used */
				background-image: url("static/img/login-01.jpg");
			
				height: auto;
			
				/* Center and scale the image nicely */
				
				background-repeat: no-repeat;
				background-size: cover;
				position: relative;
			}
			</style>
</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1 mx-auto">Review It</span>
</nav>
<center>
<br>
<div class="bg-img">
		<div class="container col-lg-6 col-sm-12">
	<div class= "mr-auto">
		<div class="alert alert-primary" role="alert">
{{ not }}  
</div>

<div class="card col-lg-8 col-sm-12">
		<img src="static/img/form-01.jpg" class="card-img-top img-fluid " height="200px">
  <div class="card-header"><h2>
   Register</h2>
  </div>
    <div class="card-body ">
    <div class>
    <form action="" method="POST" name='form' class="sm-auto">
	{% csrf_token %}
	<div class="form-group">
	<label><h4>Company:</h4></label>
	<input type="text" class="form-control form-control-lg" id="id_company" name="company" placeholder="Enter Company">
</div>
<div class="form-group">
	<label><h4>Password:</h4></label>
	<input type="password" class="form-control form-control-lg" id="id_password" name="password" placeholder="Enter Password">
</div>
<div class="form-group">	
	<label><h4>Confirm Password:</h4></label>
	<input type="password" class="form-control form-control-lg" id="id_confirm_password" name="confirm_password" placeholder="Enter Password Again"><br><br>
	<button type="submit" class="btn btn-lg btn-primary col-sm-12" style="background-color: orange;">Submit</button>
</form>
</div>
  </div>
</div>
</div>
</center>
</div>
</div>
</body>

templates/myservice.html
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head><body>
  <nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">{{ username }}</span>
  <a href="/logout" class="btn btn-primary" role="button" aria-pressed="true">Logout</a>
</nav><br><br>
  <div class="container">
<div class="col-6">
<form action="/add_service_form" style="margin-left: 200px;" method="POST" name='form'>
    {% csrf_token %}
    <label>Company:</label><br>
     <input type="text" class="form-control" id = "id_company" name="company" value="{{ username }}" placeholder="Company">
    <label>Service:</label><br>
    <input type="text" class="form-control" id = "id_service" placeholder="Name of the service" value="{{ object.service }}" name="service">
    <label>Category:</label><br>
    <input type="text" class="form-control" placeholder="Category" id = "id_category"  value="{{ object.category }}"name="category">
    <label>Description:</label><br>
    <input type="text" class="form-control" name="description" id="id_description" value="{{ object.description }}"placeholder="Description">
    <br>
  <button type="submit" class="btn btn-primary" name="sub">Submit</button> 
</form>
</div>
</div>
</body>

templates/question_div.html
{% for question in questions %}

<br />
<label class="h3" style="color:black;">{{ Question.Question }}</label>
<br /><br />
<div class="form-check form-check-inline">
  <input
    class="form-check-input"
    type="radio"
    name="review1"
    id="1"
    value="Its horrible, not going to use anymore"
    checked
  />
  <label class="form-check-label radio-inline" for="1"
    ><h5>Its horrible, not going to use anymore</h5></label
  >
</div>
<div class="form-check form-check-inline">
  <input
    class="form-check-input"
    type="radio"
    name="review1"
    id="2"
    value="Not satisfied"
  />
  <label class="form-check-label radio-inline" for="2"
    ><h5>Not satisfied</h5></label
  >
</div>
<div class="form-check form-check-inline">
  <input
    class="form-check-input"
    type="radio"
    name="review1"
    id="3"
    value="Service needs to be improved"
  />
  <label class="form-check-label radio-inline" for="3"
    ><h5>Service needs to be improved</h5></label
  >
</div>
<div class="form-check form-check-inline">
  <input
    class="form-check-input"
    type="radio"
    name="review1"
    id="4"
    value="Satisfied with the service"
  />
  <label class="form-check-label radio-inline" for="4"
    ><h5>Satisfied with the service</h5></label
  >
</div>
<div class="form-check form-check-inline">
  <input
    class="form-check-input"
    type="radio"
    name="review1"
    id="5"
    value="Its a great experience"
  />
  <label class="form-check-label radio-inline" for="5"
    ><h5>Its a great experience</h5></label
  >
</div>
<br /><br />
{% endfor %}

templates/search.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Autocomplete - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    // var availableTags = [
    //   "ActionScript",
    //   "AppleScript",
    //   "Asp",
    //   "BASIC",
    //   "C",
    //   "C++",
    //   "Clojure",
    //   "COBOL",
    //   "ColdFusion",
    //   "Erlang",
    //   "Fortran",
    //   "Groovy",
    //   "Haskell",
    //   "Java",
    //   "JavaScript",
    //   "Lisp",
    //   "Perl",
    //   "PHP",
    //   "Python",
    //   "Ruby",
    //   "Scala",
    //   "Scheme"
    // ];
    $( "#tags" ).autocomplete({
  source: [ "c++", "java", "php", "coldfusion", "javascript", "asp", "ruby" ]
});
    // $( "#tags" ).autocomplete({
    //   source: availableTags
    // });
  } );
  </script>
</head>
<body>
 
<div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags">
</div>
 
 
</body>
</html>

templates/service_category_home.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script>

        function accepted(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/accept_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

        function rejected(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/reject_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

    </script>
</head>

<body>

    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Review It</span>
        <span>Hey Admin</span>
    </nav><br><br>

    <div class="row">
        <div class="col-1"></div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Add new service Category</h3>
                    <p class="card-text"></p>
                    <br>
                    <form action="/add_category" method="post">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="Enter Service Category" name="service_category">
                        <div class="row"></div>
                        <br>
                        <input type="submit" name="submit" class="btn btn-success" value="Add">
                    </form>
                </div>
            </div>
        </div>

        <div class="col-2"></div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Service Category</h3>
                    <p class="card-text"></p>
                    <br>
                    {% for category in categories %}
                    <form action="/delete_category" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="service_category" value="{{ category.id }}">
                        <div class="container">
                            <span>{{ category.name }}</span>
                            <button class="btn btn-danger float-right">Delete</button>
                        </div>
                        <br>
                        <hr>
                    </form>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</body>

templates/test.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <style>body, html {
    
        font-family: Arial, Helvetica, sans-serif;
      }
      
      * {
        box-sizing: border-box;
      }
      
      body {
        /* The image used */
        background-image: url("static/img/organisation-01.jpg");
      
        height: 100%;
      
        /* Center and scale the image nicely */
        background-size:cover;
        background-repeat: no-repeat;
      
        position: relative;
      }
      </style>
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">{{ username }}</span>
  <a href="/logout" class="btn" style="background-color: orange;" role="button" aria-pressed="true">Logout</a>
</nav>
	<div class="container-fluid">
	
{% if error == "" %}
<a href="/login">Please Login</a>
{% else %}

<div class="row">
	<div class="col-lg-3" style="background-image: linear-gradient(to top, #136a8a 0%, #267871 99%, #267871 100%); min-height: 100%; max-height: auto">
    <br><br>
    <div class="card" style="width: 18rem;">
    
  <div class="card-body">
    <h3 class="card-title">Browse My Services.</h3>
    <p class="card-text"></p>
    {% for obj in objects %}
        <a href="/myservice/{{ obj.id }}">{{ obj.service }}</a><br>
        {% endfor %}
      </div>
      </div>
</div>
	
	<div class="col-lg-2">
		
	</div>
	<div class="col-lg-6">
    <br><br>
      <center><h2>Welcome Aboard</h2></center><br><br>
	<div class="card" style="border: 2px solid #136a8a" >
  <div class="card-body">
    <h3 class="card-title">Add a Service</h3>
    <p class="card-text"></p>
  <form action="/add_service_form" method="POST" name='form'>
  	{% csrf_token %}
  	<!-- <label>Company:</label><br> -->
    <input type="text" class="form-control form-control-lg" id = "id_company" name="company" value="{{ username }}" placeholder="Company" hidden>
     <label><h4>Service:</h4></label>
    <input type="text" class="form-control form-control-lg" id = "id_service" placeholder="Name of the service" name="service">
    <label><h4>Category:</h4></label>

    <select class="form-control form-control-lg" placeholder="Category" id = "id_category" name="category">
      {% for category in categorys %}
        <option value="{{category.name}}">{{category.name}}</option>
      {% endfor %}
    </select>
    
    <label><h4>Description:</h4></label>
    <input type="text" class="form-control form-control-lg" name="description" id="id_description" placeholder="Description">
    <br>
  <button type="submit" class="btn btn-lg " style="background-color: orange;" name="sub">Submit</button> 
</form>
       
  </div>
</div>
	</div>
</div>
{% endif %}
</div>
</body>